name: IntelliJ Plugin Release

on:
  push:
    branches:
      - intellij_release

jobs:
  publish-to-marketplace:
    name: Publish IntelliJ Plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/IntelliJPluginDemo
    permissions:
      contents: read
      packages: write

    steps:
      # Check out current repository
      - uses: actions/checkout@v2
       
      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          
      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
            
      # Configure output
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      # Run tests
      - name: Run tests
        run: |
            chmod +x ./gradlew
            ./gradlew check
            
      # Publish to marketplace
      - name: Push to market place
        run: ./gradlew publishPlugin
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
          IJ_PluginSign_PK: ${{ secrets.PRIVATE_KEY }}
          IJ_PluginSign_Pass: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          IJ_PluginSign_PublishToken: ${{ secrets.PUBLISH_TOKEN }}
          IJ_PluginSign_CertChain: ${{ secrets.CERTIFICATE_CHAIN }}