name: IntelliJ Plugin Release

on:
  push:
    branches:
      - intellij_release

jobs:
  publish-to-marketplace:
    name: Publish IntelliJ Plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/IntelliJPluginDemo
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Run tests
      run: ./gradlew test
    - name: Push to market place
      run: ./gradlew publishPlugin
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        IJ_PluginSign_PK: ${{ secrets.PRIVATE_KEY }}
        IJ_PluginSign_Pass: ${{ secrets.PRIVATE_KEY_PASSWORD }}
        IJ_PluginSign_PublishToken: ${{ secrets.PUBLISH_TOKEN }}
        IJ_PluginSign_CertChain: ${{ secrets.CERTIFICATE_CHAIN }}